# Generated by Django 4.2.7 on 2024-01-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postmodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
