# Generated by Django 4.2.7 on 2023-12-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='images/profiles/default/default-user-icon.jpg', upload_to='images/profiles/%Y/%d'),
        ),
    ]
