# Generated by Django 4.2.7 on 2024-04-24 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_postmodel_user'),
        ('comments', '0003_alter_commentmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commen', to='posts.postmodel'),
        ),
    ]
